### PR TITLE
fix bug in batch navigation

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by thet** [comment]
@petschki is this still actual? what does it solve? please provide also a changelog entry.

**Comment by petschki** [comment]
yes it is. I've came accross this in my singing & dancing channel management form, where the subscribers are listet in a crud form. you're not able to browse back to page 1 because the page numbering is starting at 1 not 0 ... i'll try to write a test for this. in addition we have to check if this is the right place to fix. maybe plone.batching should be responsible for this @tomgross ?

**Comment by jensens** [comment]
@petschki  - while I'am at it: if you rebase soon I will merge it.

**Comment by petschki** [comment]
@jensens done

**Comment by jensens** [comment]
that was a merge not a rebase ;) but well... 

tests are running...

**Comment by jensens** [comment]
ha, looks like zopefoundation packages cant be tested in PR tests. /cc @gforcada 

anyway, this change looks right and travis is green.

@petschki next time please rebase, do not pull/merge master into branches. it f***s up the diff completly.

**Comment by petschki** [comment]
Ups. Sry and thx.

**Comment by gforcada** [comment]
@jensens were do you see that zopefoundation packages can't be tested on jenkins.plone.org pull request jobs? If you give me an example I can work on it.

**Comment by jensens** [comment]
@gforcada, because of http://jenkins.plone.org/job/pull-request-5.1/182/console

**Pull request merged**
