### PR TITLE
processInputs for :records fields

### PR DESCRIPTION
**Pull request by petschki**
In order to have a feature complete form field processing, let's take `:record[s]` fields into account ... see #24

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@petschki I dont think our Jenkins CI setup watches this.

**Review by jensens — APPROVED** [review]
LGTM

**Comment by petschki** [comment]
@jensens yes I saw that ... this package should be moved to /plone I think ... see #3 ... appart from that tests are green but jenkins seems to have a problem with the build, see https://jenkins.plone.org/job/pull-request-5.2/12/ ... and Py3 tests aren't coming up at all (https://jenkins.plone.org/job/pull-request-5.2-3.7/10/console) ... stay tuned here https://github.com/plone/plone.app.caching/pull/49

**Comment by petschki** [comment]
Hm ... jenkins want's to update this PR and has no rights ... I think, in order to get the `plone.app.caching` PR green (due to the version pin here https://github.com/plone/plone.app.caching/pull/49/files#diff-2eeaed663bd0d25b7e608891384b7298R58) we should merge and release this ... @jensens what do you think?

**Comment by petschki** [comment]
Merged in fork

**Pull request closed without merging**
